features:
  enabled: true
  enforceAssignmentFor:
    - Requirement
    - Task

rules:
  titleCapitalization:
    type: regex
    targetEntities: ["Requirement", "Task"]
    field: "title"
    pattern: "^[A-Z].+"

  requirementMustHaveFeature:
    type: has-link
    fromEntity: "Requirement"
    viaField: "featureIds"
    minLinks: 1

  taskMustLinkRequirement:
    type: has-link
    fromEntity: "Task"


